version: '3.3'


services:
  keycloak.fbi.com:
    image: "quay.io/keycloak/keycloak:21.0.2"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8180
      DEBUG: "true"
      DEBUG_PORT: '*:8787'
    entrypoint: /bin/bash
    command: -c "/opt/keycloak/bin/kc.sh start-dev"
    ports:
      - "127.0.0.1:8180:8180"
      - "127.0.0.1:8787:8787"
    volumes:
      - ./providers/:/opt/keycloak/providers/
      - ../keycloak-data:/opt/keycloak/data
  nextcloud.fbi.com:
    image: nextcloud
    container_name: "nextcloud"
    environment:
      OVERWRITEHOST: "nextcloud.fbi.com:8080"
    ports:
      - "127.0.0.1:8080:80"
    links:
      - keycloak.fbi.com