version: '3.3'


services:
  keycloak.fbi.com:
    image: "quay.io/keycloak/keycloak:21.0.2"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8180
      DEBUG: "true"
      DEBUG_PORT: '*:8787'
    entrypoint: /bin/bash
    command: -c "/opt/keycloak/bin/kc.sh start-dev"
    ports:
      - "127.0.0.1:8180:8180"
      - "127.0.0.1:8787:8787"
    volumes:
      - ./providers/:/opt/keycloak/providers/
      - ../keycloak-data:/opt/keycloak/data
  wildfly.fbi.com:
    image: quay.io/wildfly/wildfly:27.0.0.Final-jdk17
    container_name: "wildfly"
    command: "/opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0"
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9990:9990"
    volumes:
      - "./deployments:/opt/jboss/wildfly/standalone/deployments"
    links:
      - keycloak.fbi.com